import { describe, expect, it } from "vitest";
import {
  buildSelectorCandidates,
  looksAutoGenerated,
  pickWinningCandidate,
} from "@shared/devtools/selectorBuilder";
import type { SelectorCandidate } from "@shared/devtools/selectorBuilder";
import type { ElementSnapshot } from "@shared/devtools/elementSnapshot";

function makeSnapshot(overrides: Partial<ElementSnapshot> = {}): ElementSnapshot {
  return {
    tagName: "div",
    classNames: [],
    attributes: {},
    nthChild: 1,
    ...overrides,
  };
}

describe("looksAutoGenerated", () => {
  it("accepts short values regardless of shape", () => {
    expect(looksAutoGenerated("btn")).toBe(false);
  });

  it("flags css-module-style hash suffixes", () => {
    expect(looksAutoGenerated("Button_root__a1b2c")).toBe(true);
  });

  it("flags long separator-free alnum strings", () => {
    expect(looksAutoGenerated("a1b2c3d4e5f6")).toBe(true);
  });

  it("does not flag kebab-case identifiers", () => {
    expect(looksAutoGenerated("generate-button")).toBe(false);
  });

  it("does not flag readable camelCase identifiers without digits", () => {
    expect(looksAutoGenerated("promptTextArea")).toBe(false);
  });
});

describe("buildSelectorCandidates", () => {
  it("prefers data-testid highest", () => {
    const target = makeSnapshot({
      tagName: "button",
      attributes: { "data-testid": "generate-btn" },
    });
    const candidates = buildSelectorCandidates(target, []);
    expect(candidates[0]).toMatchObject({
      selector: 'button[data-testid="generate-btn"]',
      confidence: "high",
    });
  });

  it("includes aria-label as a high-confidence candidate", () => {
    const target = makeSnapshot({ tagName: "button", attributes: { "aria-label": "Generate" } });
    const candidates = buildSelectorCandidates(target, []);
    expect(
      candidates.some(
        (c) => c.selector === 'button[aria-label="Generate"]' && c.confidence === "high",
      ),
    ).toBe(true);
  });

  it("ranks a stable id as high confidence", () => {
    const target = makeSnapshot({ tagName: "textarea", id: "prompt-box" });
    const candidates = buildSelectorCandidates(target, []);
    expect(candidates.some((c) => c.selector === "#prompt-box" && c.confidence === "high")).toBe(
      true,
    );
  });

  it("ranks an auto-generated-looking id as low confidence", () => {
    const target = makeSnapshot({ tagName: "textarea", id: "ember482x9z1" });
    const candidates = buildSelectorCandidates(target, []);
    const idCandidate = candidates.find((c) => c.selector === "#ember482x9z1");
    expect(idCandidate?.confidence).toBe("low");
  });

  it("escapes quotes inside attribute values", () => {
    const target = makeSnapshot({ tagName: "button", attributes: { "aria-label": 'Say "hi"' } });
    const candidates = buildSelectorCandidates(target, []);
    expect(candidates[0]?.selector).toBe('button[aria-label="Say \\"hi\\""]');
  });

  it("filters out auto-generated-looking classes but keeps stable ones", () => {
    const target = makeSnapshot({
      tagName: "button",
      classNames: ["Button_root__a1b2c", "primary-action"],
    });
    const candidates = buildSelectorCandidates(target, []);
    const classCandidate = candidates.find((c) => c.reason === "class names");
    expect(classCandidate?.selector).toBe("button.primary-action");
  });

  it("omits the class candidate entirely when every class looks auto-generated", () => {
    const target = makeSnapshot({ tagName: "button", classNames: ["a1b2c3d4e5f6"] });
    const candidates = buildSelectorCandidates(target, []);
    expect(candidates.some((c) => c.reason === "class names")).toBe(false);
  });

  it("always includes a positional fallback candidate", () => {
    const target = makeSnapshot({ tagName: "button", nthChild: 2 });
    const candidates = buildSelectorCandidates(target, []);
    const fallback = candidates.at(-1);
    expect(fallback?.reason).toBe("positional path (last resort)");
    expect(fallback?.selector).toBe("button:nth-child(2)");
  });

  it("builds a positional fallback that walks the ancestor chain", () => {
    const target = makeSnapshot({ tagName: "button", nthChild: 3 });
    const ancestors: ElementSnapshot[] = [
      makeSnapshot({ tagName: "div", nthChild: 1 }),
      makeSnapshot({ tagName: "section", nthChild: 2 }),
    ];
    const candidates = buildSelectorCandidates(target, ancestors);
    const fallback = candidates.at(-1);
    expect(fallback?.selector).toBe(
      "section:nth-child(2) > div:nth-child(1) > button:nth-child(3)",
    );
  });

  it("stops the positional fallback at the nearest stable-id ancestor", () => {
    const target = makeSnapshot({ tagName: "button", nthChild: 3 });
    const ancestors: ElementSnapshot[] = [
      makeSnapshot({ tagName: "div", nthChild: 1, id: "toolbar" }),
      makeSnapshot({ tagName: "section", nthChild: 2 }),
    ];
    const candidates = buildSelectorCandidates(target, ancestors);
    const fallback = candidates.at(-1);
    expect(fallback?.selector).toBe("#toolbar > button:nth-child(3)");
  });

  it("produces a selector for a plain element with nothing stable at all", () => {
    const target = makeSnapshot({ tagName: "div", nthChild: 5 });
    const candidates = buildSelectorCandidates(target, []);
    expect(candidates).toHaveLength(1);
    expect(candidates[0]?.selector).toBe("div:nth-child(5)");
  });
});

describe("pickWinningCandidate", () => {
  function candidate(selector: string): SelectorCandidate {
    return { selector, confidence: "high", reason: "test" };
  }

  it("picks the first candidate that's unique", () => {
    const candidates = [candidate("a"), candidate("b"), candidate("c")];
    const result = pickWinningCandidate(candidates, (selector) => selector === "b");
    expect(result).toEqual({ candidate: candidate("b"), guaranteedUnique: true });
  });

  it("returns the first candidate immediately when it's already unique", () => {
    const candidates = [candidate("a"), candidate("b")];
    const result = pickWinningCandidate(candidates, () => true);
    expect(result.candidate.selector).toBe("a");
    expect(result.guaranteedUnique).toBe(true);
  });

  it("falls back to the last candidate, flagged unguaranteed, when nothing is unique", () => {
    const candidates = [candidate("a"), candidate("b"), candidate("fallback")];
    const result = pickWinningCandidate(candidates, () => false);
    expect(result).toEqual({ candidate: candidate("fallback"), guaranteedUnique: false });
  });
});
