import type { ElementSnapshot } from "./elementSnapshot";

export type SelectorConfidence = "high" | "medium" | "low";

export interface SelectorCandidate {
  selector: string;
  confidence: SelectorConfidence;
  reason: string;
}

interface StableAttribute {
  name: string;
  confidence: SelectorConfidence;
}

const STABLE_ATTRIBUTES: readonly StableAttribute[] = [
  { name: "data-testid", confidence: "high" },
  { name: "data-test-id", confidence: "high" },
  { name: "data-test", confidence: "high" },
  { name: "aria-label", confidence: "high" },
  { name: "name", confidence: "medium" },
  { name: "placeholder", confidence: "medium" },
  { name: "role", confidence: "medium" },
];

/**
 * Flags ids/classes that look machine-generated (hashed CSS-module suffixes,
 * long runs of mixed letters+digits with no separators) so they get ranked
 * below genuinely stable identifiers — a heuristic aid only. The real safety
 * net is the live uniqueness check the content script runs against the
 * actual page before accepting any candidate.
 */
export function looksAutoGenerated(value: string): boolean {
  if (value.length < 6) {
    return false;
  }
  if (/__[a-z0-9]{4,10}$/i.test(value)) {
    return true;
  }
  const hasSeparator = /[-_ :.]/.test(value);
  const hasDigit = /\d/.test(value);
  const hasLetter = /[a-z]/i.test(value);
  return !hasSeparator && hasDigit && hasLetter && value.length >= 8;
}

function escapeAttributeValue(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function escapeIdentifier(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9_-]/g, (char) => `\\${char}`)
    .replace(/^(\d)/, (digit) => `\\3${digit} `);
}

function buildPositionalSelector(
  target: ElementSnapshot,
  ancestors: readonly ElementSnapshot[],
): string {
  const chain = [target, ...ancestors];
  const segments: string[] = [];
  for (const node of chain) {
    if (node.id && !looksAutoGenerated(node.id)) {
      segments.unshift(`#${escapeIdentifier(node.id)}`);
      break;
    }
    segments.unshift(`${node.tagName.toLowerCase()}:nth-child(${String(node.nthChild)})`);
  }
  return segments.join(" > ");
}

/**
 * Produces ranked selector candidates for `target`, most stable first. Never
 * hardcodes anything about Google Flow specifically — it only reasons about
 * the attributes/ids/classes/position it's handed. The caller (the content
 * script, which has a real document) is responsible for testing each
 * candidate against the live page and keeping the first one that uniquely
 * matches; the positional fallback at the end is always structurally unique
 * given a correct ancestor chain, so the list always has a usable last resort.
 */
export function buildSelectorCandidates(
  target: ElementSnapshot,
  ancestors: readonly ElementSnapshot[],
): SelectorCandidate[] {
  const tag = target.tagName.toLowerCase();
  const candidates: SelectorCandidate[] = [];

  for (const attribute of STABLE_ATTRIBUTES) {
    const value = target.attributes[attribute.name];
    if (value) {
      candidates.push({
        selector: `${tag}[${attribute.name}="${escapeAttributeValue(value)}"]`,
        confidence: attribute.confidence,
        reason: `${attribute.name} attribute`,
      });
    }
  }

  if (target.id) {
    const autoGenerated = looksAutoGenerated(target.id);
    candidates.push({
      selector: `#${escapeIdentifier(target.id)}`,
      confidence: autoGenerated ? "low" : "high",
      reason: autoGenerated ? "id attribute (looks auto-generated)" : "id attribute",
    });
  }

  const stableClasses = target.classNames.filter((className) => !looksAutoGenerated(className));
  if (stableClasses.length > 0) {
    candidates.push({
      selector: `${tag}.${stableClasses.map(escapeIdentifier).join(".")}`,
      confidence: "medium",
      reason: "class names",
    });
  }

  if (target.attributes.type && (tag === "input" || tag === "button")) {
    candidates.push({
      selector: `${tag}[type="${escapeAttributeValue(target.attributes.type)}"]`,
      confidence: "low",
      reason: "type attribute",
    });
  }

  candidates.push({
    selector: buildPositionalSelector(target, ancestors),
    confidence: "low",
    reason: "positional path (last resort)",
  });

  return candidates;
}

export interface WinningCandidate {
  candidate: SelectorCandidate;
  /** False when even the positional fallback couldn't be confirmed unique against the live page. */
  guaranteedUnique: boolean;
}

/**
 * Picks the first candidate that uniquely matches the real element, using
 * `isUnique` (backed by the live document's querySelectorAll in the content
 * script) rather than guessing. Always returns something — the last
 * candidate is the positional fallback, which is unique in the overwhelming
 * majority of real pages, but repeated structures (e.g. list items) can
 * still collide, so `guaranteedUnique` tells the caller whether to surface
 * that risk to the user.
 */
export function pickWinningCandidate(
  candidates: readonly SelectorCandidate[],
  isUnique: (selector: string) => boolean,
): WinningCandidate {
  for (const candidate of candidates) {
    if (isUnique(candidate.selector)) {
      return { candidate, guaranteedUnique: true };
    }
  }
  const last = candidates.at(-1);
  if (!last) {
    throw new Error("buildSelectorCandidates always returns at least one candidate.");
  }
  return { candidate: last, guaranteedUnique: false };
}
